_core:
  default_config_hash: wbD9a1lSFlzefyZbT7berzkarufh5L0yc5p0e9pywE4
langcode: en-gb
version: v3
disabled: false
rest_api_url: 'https://xxxx-xxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx.luna.akamaiapis.net/'
storage_method: file
client_token: loquate_key
client_secret: loquate_key
access_token: loquate_key
edgerc_path: /home/millboard/.edgerc
edgerc_section: default
basepath: www.millboard.com
timeout: 5
domain:
  production: true
  staging: false
action_v3:
  delete: true
  invalidate: false
log_requests: false
edge_cache_tag_header: false
purge_urls_with_hostname: false
edge_cache_tag_header_blacklist: {  }
edgescape_support: false
