sites:
  default:
    modules:
      - acquia_cms_site_studio
      - acquia_cms_page
      - acquia_cms_search
      - acquia_cms_tour
      - acquia_cms_toolbar
      - acquia_cms_dam
      - gdpr
      - eu_cookie_compliance
      - gdpr_fields
    starter_kit: acquia_cms_enterprise_low_code
    themes:
      admin: acquia_claro
      default: cohesion_theme
