millboard_sap_configuration.sap_mail_configuration:
  path: '/admin/config/millboard_sap_configuration/sap_mail_configuration'
  defaults:
    _form: '\Drupal\millboard_sap_configuration\Form\SapMailConfiguration'
    _title: 'Millboard SAP E-mail Settings'
  requirements:
    _permission: 'administer site configuration'
