millboard_sap_configuration.sap_mail_configuration:
  title: 'SAP Mail Configuration'
  description: 'Configure Millboard SAP mail Configuration.'
  parent: system.admin_config_services
  route_name: millboard_sap_configuration.sap_mail_configuration
  weight: 100
